export enum SetupStagesEnum {
  START = "START",
  ENABLE_MOTION = "ENABLE_MOTION",
  SELECT_MODE = "SELECT_MODE",
  CONNECT_HEADPHONES = "CONNECT_HEADPHONES",
  HEADPHONES_TRAINING = "HEADPHONES_TRAINING",
  PHONE_TRAINING = "PHONE_TRAINING",
  ENABLE_NOTIFICATIONS = "ENABLE_NOTIFICATIONS",
  SET_UP_GOAL = "SET_UP_GOAL",
}

export type SetupStagesType = `${SetupStagesEnum}`;
