import { BadgeType } from "./interfaces/badges.types";

const badges: BadgeType[] = [
  {
    id: 1,
    title: "1k",
    subtitle: "XP Champion",
    description: "1,000 XP",
    badge: "xp",
    message: "You've aced your way to 1000 XP! Keep up the excellent work!",
    color: "#7457DD",
  },
  {
    id: 2,
    title: "20",
    subtitle: "Community Builder",
    description: "20 Friends",
    badge: "challenge",
    message: "You've aced your way to 1000 XP! Keep up the excellent work!",
    color: "#4DB87A",
  },
  {
    id: 3,
    title: "7",
    subtitle: "Streak Master",
    description: "7 Days",
    badge: "streak",
    message: "You've aced your way to 1000 XP! Keep up the excellent work!",
    color: "#FD9226",
  },
  {
    id: 4,
    title: "?",
    subtitle: "???",
    description: "??????",
    badge: "dummy-badge",
    message: "You've aced your way to 1000 XP! Keep up the excellent work!",
  },
  {
    id: 5,
    title: "?",
    subtitle: "???",
    description: "??????",
    badge: "dummy-badge",
    message: "You've aced your way to 1000 XP! Keep up the excellent work!",
  },
  {
    id: 6,
    title: "?",
    subtitle: "???",
    description: "??????",
    badge: "dummy-badge",
    message: "You've aced your way to 1000 XP! Keep up the excellent work!",
  },
  {
    id: 7,
    title: "?",
    subtitle: "???",
    description: "??????",
    badge: "dummy-badge",
    message: "You've aced your way to 1000 XP! Keep up the excellent work!",
  },
  {
    id: 8,
    title: "?",
    subtitle: "???",
    description: "??????",
    badge: "dummy-badge",
    message: "You've aced your way to 1000 XP! Keep up the excellent work!",
  },
  {
    id: 9,
    title: "?",
    subtitle: "???",
    description: "??????",
    badge: "dummy-badge",
    message: "You've aced your way to 1000 XP! Keep up the excellent work!",
  },
];

export default badges;
